name: build-native

on:
  workflow_dispatch:

jobs:
  bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: ./scripts/build-bridge.sh release
